/**
 **************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Analog to Digital Conversion multiple channel
 **************************
 */


//#include <stm32f401xe.h>
#include "stm32f4xx.h"
//#include "delay.h"

#define GPIOAEN		(1U<<0)
#define ADC1EN		(1U<<8)			//enable ADC1 CLOCK ON PG NO -122
#define ADON		(1U<<0)			//conversion start ADC1 on pg - 232
#define CONT		(1U<<1)			//set the continuous conversion,
						//for not using external trigger to start adc conversion
#define SWSTART		(1U<<30)		//start conversion for regular channel.
#define EOC_FLAG	(1U<<1)			//end of conversion without any use of dma or overrun on pg no 229.


int main(void)
{
	// enable the clock access for GPIOA and ADC
	RCC -> AHB1ENR |= GPIOAEN;
	RCC -> APB2ENR |= ADC1EN;

	// GPIOA Configurations
	GPIOA -> MODER |= (1U<<2)|(1U<<3)|(1U<<4)|(1U<<5);// setup PA1 and PA2 as analog pin

	// ADC Configurations
	ADC1 -> SQR1 = 0;			// Setup the length as 1


	//ADC1 -> SQR3 |= (1U<<0)|(1U<<6); 	// SQ1 is set as Channel 1 and SQ2 as Channel 2

	ADC1 -> CR2 |= ADON;				// Enable the ADC Peripheral
	//ADC1 -> CR2 |= CONT; 				// Continuous Conversion the ADC Conversion
	while (1)
	{
		ADC1 -> CR2 |= SWSTART;				// start conversion
		ADC1 -> SQR3 = (1U<<0);				// for pa1 pin no.
		// Start the ADC Conversion
		while ((ADC1 -> SR & EOC_FLAG)==0)
		{//wait here till the ADC Conversion is not complete/}
		// once ADC Conversion is complete, obtain the data from DR
		_delay_ms(100);
		ADC1 -> CR2 |= SWSTART;
		ADC1 -> SQR3 = (1U<<1);				// for pin 2
		// Start the ADC Conversion
		while ((ADC1 -> SR & EOC_FLAG)==0)
		{/wait here till the ADC Conversion is not complete/}
		// once ADC Conversion is complete, obtain the data from DR
		_delay_ms(100);
	}
}
